package gay.depau.tzdb_generator

// SPDX-License-Identifier: Apache-2.0
// This file is part of World Clock Tile.

val countryNameFixups = mapOf(
    "Congo (Kinshasa)" to "DR Congo (Kinshasa)",
    "Federated States of Micronesia" to "Micronesia",
    "Northern Cyprus" to "Cyprus",
    "The Bahamas" to "Bahamas",
    "The Gambia" to "Gambia",
    "United States Virgin Islands" to "United States of America",
    "Vatican (Holy Sea)" to "Vatican City",
    "Faroe Islands" to "Denmark",
    "Aland" to "Finland",
    "Isle of Man" to "United Kingdom",
    "Somaliland" to "Somalia",
    "Hong Kong S.A.R." to "Hong Kong",
    "Macau S.A.R" to "Macau",
)

val tzNameFixups = mapOf(
    "Europe/Kyiv" to "Europe/Kiev",
    "America/Ciudad_Juarez" to "America/Boise",
)

val missingProvinces = mapOf(
    "Spain" to "Islands",
    "United States of America" to "Illinois", // Oak Park is missing the state
    "Colombia" to "San Andrés y Providencia", // San Andrés is missing the department
)

// These are the timezones recognized by Android on my watch
val androidTimezoneNames = listOf(
    "Africa/Abidjan",
    "Africa/Accra",
    "Africa/Addis_Ababa",
    "Africa/Algiers",
    "Africa/Asmara",
    "Africa/Asmera",
    "Africa/Bamako",
    "Africa/Bangui",
    "Africa/Banjul",
    "Africa/Bissau",
    "Africa/Blantyre",
    "Africa/Brazzaville",
    "Africa/Bujumbura",
    "Africa/Cairo",
    "Africa/Casablanca",
    "Africa/Ceuta",
    "Africa/Conakry",
    "Africa/Dakar",
    "Africa/Dar_es_Salaam",
    "Africa/Djibouti",
    "Africa/Douala",
    "Africa/El_Aaiun",
    "Africa/Freetown",
    "Africa/Gaborone",
    "Africa/Harare",
    "Africa/Johannesburg",
    "Africa/Juba",
    "Africa/Kampala",
    "Africa/Khartoum",
    "Africa/Kigali",
    "Africa/Kinshasa",
    "Africa/Lagos",
    "Africa/Libreville",
    "Africa/Lome",
    "Africa/Luanda",
    "Africa/Lubumbashi",
    "Africa/Lusaka",
    "Africa/Malabo",
    "Africa/Maputo",
    "Africa/Maseru",
    "Africa/Mbabane",
    "Africa/Mogadishu",
    "Africa/Monrovia",
    "Africa/Nairobi",
    "Africa/Ndjamena",
    "Africa/Niamey",
    "Africa/Nouakchott",
    "Africa/Ouagadougou",
    "Africa/Porto-Novo",
    "Africa/Sao_Tome",
    "Africa/Timbuktu",
    "Africa/Tripoli",
    "Africa/Tunis",
    "Africa/Windhoek",
    "America/Adak",
    "America/Anchorage",
    "America/Anguilla",
    "America/Antigua",
    "America/Araguaina",
    "America/Argentina/Buenos_Aires",
    "America/Argentina/Catamarca",
    "America/Argentina/ComodRivadavia",
    "America/Argentina/Cordoba",
    "America/Argentina/Jujuy",
    "America/Argentina/La_Rioja",
    "America/Argentina/Mendoza",
    "America/Argentina/Rio_Gallegos",
    "America/Argentina/Salta",
    "America/Argentina/San_Juan",
    "America/Argentina/San_Luis",
    "America/Argentina/Tucuman",
    "America/Argentina/Ushuaia",
    "America/Aruba",
    "America/Asuncion",
    "America/Atikokan",
    "America/Atka",
    "America/Bahia",
    "America/Bahia_Banderas",
    "America/Barbados",
    "America/Belem",
    "America/Belize",
    "America/Blanc-Sablon",
    "America/Boa_Vista",
    "America/Bogota",
    "America/Boise",
    "America/Buenos_Aires",
    "America/Cambridge_Bay",
    "America/Campo_Grande",
    "America/Cancun",
    "America/Caracas",
    "America/Catamarca",
    "America/Cayenne",
    "America/Cayman",
    "America/Chicago",
    "America/Chihuahua",
    "America/Coral_Harbour",
    "America/Cordoba",
    "America/Costa_Rica",
    "America/Creston",
    "America/Cuiaba",
    "America/Curacao",
    "America/Danmarkshavn",
    "America/Dawson",
    "America/Dawson_Creek",
    "America/Denver",
    "America/Detroit",
    "America/Dominica",
    "America/Edmonton",
    "America/Eirunepe",
    "America/El_Salvador",
    "America/Ensenada",
    "America/Fort_Nelson",
    "America/Fort_Wayne",
    "America/Fortaleza",
    "America/Glace_Bay",
    "America/Godthab",
    "America/Goose_Bay",
    "America/Grand_Turk",
    "America/Grenada",
    "America/Guadeloupe",
    "America/Guatemala",
    "America/Guayaquil",
    "America/Guyana",
    "America/Halifax",
    "America/Havana",
    "America/Hermosillo",
    "America/Indiana/Indianapolis",
    "America/Indiana/Knox",
    "America/Indiana/Marengo",
    "America/Indiana/Petersburg",
    "America/Indiana/Tell_City",
    "America/Indiana/Vevay",
    "America/Indiana/Vincennes",
    "America/Indiana/Winamac",
    "America/Indianapolis",
    "America/Inuvik",
    "America/Iqaluit",
    "America/Jamaica",
    "America/Jujuy",
    "America/Juneau",
    "America/Kentucky/Louisville",
    "America/Kentucky/Monticello",
    "America/Knox_IN",
    "America/Kralendijk",
    "America/La_Paz",
    "America/Lima",
    "America/Los_Angeles",
    "America/Louisville",
    "America/Lower_Princes",
    "America/Maceio",
    "America/Managua",
    "America/Manaus",
    "America/Marigot",
    "America/Martinique",
    "America/Matamoros",
    "America/Mazatlan",
    "America/Mendoza",
    "America/Menominee",
    "America/Merida",
    "America/Metlakatla",
    "America/Mexico_City",
    "America/Miquelon",
    "America/Moncton",
    "America/Monterrey",
    "America/Montevideo",
    "America/Montreal",
    "America/Montserrat",
    "America/Nassau",
    "America/New_York",
    "America/Nipigon",
    "America/Nome",
    "America/Noronha",
    "America/North_Dakota/Beulah",
    "America/North_Dakota/Center",
    "America/North_Dakota/New_Salem",
    "America/Nuuk",
    "America/Ojinaga",
    "America/Panama",
    "America/Pangnirtung",
    "America/Paramaribo",
    "America/Phoenix",
    "America/Port-au-Prince",
    "America/Port_of_Spain",
    "America/Porto_Acre",
    "America/Porto_Velho",
    "America/Puerto_Rico",
    "America/Punta_Arenas",
    "America/Rainy_River",
    "America/Rankin_Inlet",
    "America/Recife",
    "America/Regina",
    "America/Resolute",
    "America/Rio_Branco",
    "America/Rosario",
    "America/Santa_Isabel",
    "America/Santarem",
    "America/Santiago",
    "America/Santo_Domingo",
    "America/Sao_Paulo",
    "America/Scoresbysund",
    "America/Shiprock",
    "America/Sitka",
    "America/St_Barthelemy",
    "America/St_Johns",
    "America/St_Kitts",
    "America/St_Lucia",
    "America/St_Thomas",
    "America/St_Vincent",
    "America/Swift_Current",
    "America/Tegucigalpa",
    "America/Thule",
    "America/Thunder_Bay",
    "America/Tijuana",
    "America/Toronto",
    "America/Tortola",
    "America/Vancouver",
    "America/Virgin",
    "America/Whitehorse",
    "America/Winnipeg",
    "America/Yakutat",
    "America/Yellowknife",
    "Antarctica/Casey",
    "Antarctica/Davis",
    "Antarctica/DumontDUrville",
    "Antarctica/Macquarie",
    "Antarctica/Mawson",
    "Antarctica/McMurdo",
    "Antarctica/Palmer",
    "Antarctica/Rothera",
    "Antarctica/South_Pole",
    "Antarctica/Syowa",
    "Antarctica/Troll",
    "Antarctica/Vostok",
    "Arctic/Longyearbyen",
    "Asia/Aden",
    "Asia/Almaty",
    "Asia/Amman",
    "Asia/Anadyr",
    "Asia/Aqtau",
    "Asia/Aqtobe",
    "Asia/Ashgabat",
    "Asia/Ashkhabad",
    "Asia/Atyrau",
    "Asia/Baghdad",
    "Asia/Bahrain",
    "Asia/Baku",
    "Asia/Bangkok",
    "Asia/Barnaul",
    "Asia/Beirut",
    "Asia/Bishkek",
    "Asia/Brunei",
    "Asia/Calcutta",
    "Asia/Chita",
    "Asia/Choibalsan",
    "Asia/Chongqing",
    "Asia/Chungking",
    "Asia/Colombo",
    "Asia/Dacca",
    "Asia/Damascus",
    "Asia/Dhaka",
    "Asia/Dili",
    "Asia/Dubai",
    "Asia/Dushanbe",
    "Asia/Famagusta",
    "Asia/Gaza",
    "Asia/Harbin",
    "Asia/Hebron",
    "Asia/Ho_Chi_Minh",
    "Asia/Hong_Kong",
    "Asia/Hovd",
    "Asia/Irkutsk",
    "Asia/Istanbul",
    "Asia/Jakarta",
    "Asia/Jayapura",
    "Asia/Jerusalem",
    "Asia/Kabul",
    "Asia/Kamchatka",
    "Asia/Karachi",
    "Asia/Kashgar",
    "Asia/Kathmandu",
    "Asia/Katmandu",
    "Asia/Khandyga",
    "Asia/Kolkata",
    "Asia/Krasnoyarsk",
    "Asia/Kuala_Lumpur",
    "Asia/Kuching",
    "Asia/Kuwait",
    "Asia/Macao",
    "Asia/Macau",
    "Asia/Magadan",
    "Asia/Makassar",
    "Asia/Manila",
    "Asia/Muscat",
    "Asia/Nicosia",
    "Asia/Novokuznetsk",
    "Asia/Novosibirsk",
    "Asia/Omsk",
    "Asia/Oral",
    "Asia/Phnom_Penh",
    "Asia/Pontianak",
    "Asia/Pyongyang",
    "Asia/Qatar",
    "Asia/Qostanay",
    "Asia/Qyzylorda",
    "Asia/Rangoon",
    "Asia/Riyadh",
    "Asia/Saigon",
    "Asia/Sakhalin",
    "Asia/Samarkand",
    "Asia/Seoul",
    "Asia/Shanghai",
    "Asia/Singapore",
    "Asia/Srednekolymsk",
    "Asia/Taipei",
    "Asia/Tashkent",
    "Asia/Tbilisi",
    "Asia/Tehran",
    "Asia/Tel_Aviv",
    "Asia/Thimbu",
    "Asia/Thimphu",
    "Asia/Tokyo",
    "Asia/Tomsk",
    "Asia/Ujung_Pandang",
    "Asia/Ulaanbaatar",
    "Asia/Ulan_Bator",
    "Asia/Urumqi",
    "Asia/Ust-Nera",
    "Asia/Vientiane",
    "Asia/Vladivostok",
    "Asia/Yakutsk",
    "Asia/Yangon",
    "Asia/Yekaterinburg",
    "Asia/Yerevan",
    "Atlantic/Azores",
    "Atlantic/Bermuda",
    "Atlantic/Canary",
    "Atlantic/Cape_Verde",
    "Atlantic/Faeroe",
    "Atlantic/Faroe",
    "Atlantic/Jan_Mayen",
    "Atlantic/Madeira",
    "Atlantic/Reykjavik",
    "Atlantic/South_Georgia",
    "Atlantic/St_Helena",
    "Atlantic/Stanley",
    "Australia/ACT",
    "Australia/Adelaide",
    "Australia/Brisbane",
    "Australia/Broken_Hill",
    "Australia/Canberra",
    "Australia/Currie",
    "Australia/Darwin",
    "Australia/Eucla",
    "Australia/Hobart",
    "Australia/LHI",
    "Australia/Lindeman",
    "Australia/Lord_Howe",
    "Australia/Melbourne",
    "Australia/NSW",
    "Australia/North",
    "Australia/Perth",
    "Australia/Queensland",
    "Australia/South",
    "Australia/Sydney",
    "Australia/Tasmania",
    "Australia/Victoria",
    "Australia/West",
    "Australia/Yancowinna",
    "Brazil/Acre",
    "Brazil/DeNoronha",
    "Brazil/East",
    "Brazil/West",
    "CET",
    "CST6CDT",
    "Canada/Atlantic",
    "Canada/Central",
    "Canada/Eastern",
    "Canada/Mountain",
    "Canada/Newfoundland",
    "Canada/Pacific",
    "Canada/Saskatchewan",
    "Canada/Yukon",
    "Chile/Continental",
    "Chile/EasterIsland",
    "Cuba",
    "EET",
    "EST",
    "EST5EDT",
    "Egypt",
    "Eire",
    "Etc/GMT",
    "Etc/GMT+0",
    "Etc/GMT+1",
    "Etc/GMT+10",
    "Etc/GMT+11",
    "Etc/GMT+12",
    "Etc/GMT+2",
    "Etc/GMT+3",
    "Etc/GMT+4",
    "Etc/GMT+5",
    "Etc/GMT+6",
    "Etc/GMT+7",
    "Etc/GMT+8",
    "Etc/GMT+9",
    "Etc/GMT-0",
    "Etc/GMT-1",
    "Etc/GMT-10",
    "Etc/GMT-11",
    "Etc/GMT-12",
    "Etc/GMT-13",
    "Etc/GMT-14",
    "Etc/GMT-2",
    "Etc/GMT-3",
    "Etc/GMT-4",
    "Etc/GMT-5",
    "Etc/GMT-6",
    "Etc/GMT-7",
    "Etc/GMT-8",
    "Etc/GMT-9",
    "Etc/GMT0",
    "Etc/Greenwich",
    "Etc/UCT",
    "Etc/UTC",
    "Etc/Universal",
    "Etc/Zulu",
    "Europe/Amsterdam",
    "Europe/Andorra",
    "Europe/Astrakhan",
    "Europe/Athens",
    "Europe/Belfast",
    "Europe/Belgrade",
    "Europe/Berlin",
    "Europe/Bratislava",
    "Europe/Brussels",
    "Europe/Bucharest",
    "Europe/Budapest",
    "Europe/Busingen",
    "Europe/Chisinau",
    "Europe/Copenhagen",
    "Europe/Dublin",
    "Europe/Gibraltar",
    "Europe/Guernsey",
    "Europe/Helsinki",
    "Europe/Isle_of_Man",
    "Europe/Istanbul",
    "Europe/Jersey",
    "Europe/Kaliningrad",
    "Europe/Kiev",
    "Europe/Kirov",
    "Europe/Lisbon",
    "Europe/Ljubljana",
    "Europe/London",
    "Europe/Luxembourg",
    "Europe/Madrid",
    "Europe/Malta",
    "Europe/Mariehamn",
    "Europe/Minsk",
    "Europe/Monaco",
    "Europe/Moscow",
    "Europe/Nicosia",
    "Europe/Oslo",
    "Europe/Paris",
    "Europe/Podgorica",
    "Europe/Prague",
    "Europe/Riga",
    "Europe/Rome",
    "Europe/Samara",
    "Europe/San_Marino",
    "Europe/Sarajevo",
    "Europe/Saratov",
    "Europe/Simferopol",
    "Europe/Skopje",
    "Europe/Sofia",
    "Europe/Stockholm",
    "Europe/Tallinn",
    "Europe/Tirane",
    "Europe/Tiraspol",
    "Europe/Ulyanovsk",
    "Europe/Uzhgorod",
    "Europe/Vaduz",
    "Europe/Vatican",
    "Europe/Vienna",
    "Europe/Vilnius",
    "Europe/Volgograd",
    "Europe/Warsaw",
    "Europe/Zagreb",
    "Europe/Zaporozhye",
    "Europe/Zurich",
    "GB",
    "GB-Eire",
    "GMT",
    "GMT+0",
    "GMT-0",
    "GMT0",
    "Greenwich",
    "HST",
    "Hongkong",
    "Iceland",
    "Indian/Antananarivo",
    "Indian/Chagos",
    "Indian/Christmas",
    "Indian/Cocos",
    "Indian/Comoro",
    "Indian/Kerguelen",
    "Indian/Mahe",
    "Indian/Maldives",
    "Indian/Mauritius",
    "Indian/Mayotte",
    "Indian/Reunion",
    "Iran",
    "Israel",
    "Jamaica",
    "Japan",
    "Kwajalein",
    "Libya",
    "MET",
    "MST",
    "MST7MDT",
    "Mexico/BajaNorte",
    "Mexico/BajaSur",
    "Mexico/General",
    "NZ",
    "NZ-CHAT",
    "Navajo",
    "PRC",
    "PST8PDT",
    "Pacific/Apia",
    "Pacific/Auckland",
    "Pacific/Bougainville",
    "Pacific/Chatham",
    "Pacific/Chuuk",
    "Pacific/Easter",
    "Pacific/Efate",
    "Pacific/Enderbury",
    "Pacific/Fakaofo",
    "Pacific/Fiji",
    "Pacific/Funafuti",
    "Pacific/Galapagos",
    "Pacific/Gambier",
    "Pacific/Guadalcanal",
    "Pacific/Guam",
    "Pacific/Honolulu",
    "Pacific/Johnston",
    "Pacific/Kanton",
    "Pacific/Kiritimati",
    "Pacific/Kosrae",
    "Pacific/Kwajalein",
    "Pacific/Majuro",
    "Pacific/Marquesas",
    "Pacific/Midway",
    "Pacific/Nauru",
    "Pacific/Niue",
    "Pacific/Norfolk",
    "Pacific/Noumea",
    "Pacific/Pago_Pago",
    "Pacific/Palau",
    "Pacific/Pitcairn",
    "Pacific/Pohnpei",
    "Pacific/Ponape",
    "Pacific/Port_Moresby",
    "Pacific/Rarotonga",
    "Pacific/Saipan",
    "Pacific/Samoa",
    "Pacific/Tahiti",
    "Pacific/Tarawa",
    "Pacific/Tongatapu",
    "Pacific/Truk",
    "Pacific/Wake",
    "Pacific/Wallis",
    "Pacific/Yap",
    "Poland",
    "Portugal",
    "ROC",
    "ROK",
    "Singapore",
    "Turkey",
    "UCT",
    "US/Alaska",
    "US/Aleutian",
    "US/Arizona",
    "US/Central",
    "US/East-Indiana",
    "US/Eastern",
    "US/Hawaii",
    "US/Indiana-Starke",
    "US/Michigan",
    "US/Mountain",
    "US/Pacific",
    "US/Samoa",
    "UTC",
    "Universal",
    "W-SU",
    "WET",
    "Zulu",
)


// Missing ones are "provinces"
val provincesDenominations = mapOf(
    "Albania" to "counties",
    "Andorra" to "parishes",
    "Armenia" to "marzer",
    "Australia" to "states",
    "Austria" to "states",
    "Azerbaijan" to "districts",
    "Bahamas" to "districts",
    "Bahrain" to "governorates",
    "Bangladesh" to "divisions",
    "Barbados" to "parishes",
    "Belarus" to "oblasts",
    "Belgium" to "regions",
    "Belize" to "districts",
    "Benin" to "departments",
    "Bhutan" to "districts",
    "Bolivia" to "departments",
    "Bosnia and Herzegovina" to "entities",
    "Botswana" to "districts",
    "Brazil" to "states",
    "Brunei" to "districts",
    "Bulgaria" to "oblasts",
    "Burkina Faso" to "regions",
    "Cameroon" to "regions",
    "Cape Verde" to "municipalities",
    "Central African Republic" to "prefectures",
    "Chad" to "regions",
    "Chile" to "regions",
    "Colombia" to "departments",
    "Comoros" to "islands",
    "Congo (Brazzaville)" to "departments",
    "Croatia" to "counties",
    "Cyprus" to "districts",
    "Czech Republic" to "regions",
    "Denmark" to "regions",
    "Djibouti" to "regions",
    "Dominica" to "parishes",
    "East Timor" to "municipalities",
    "Egypt" to "governorates",
    "El Salvador" to "departments",
    "Eritrea" to "regions",
    "Estonia" to "counties",
    "Ethiopia" to "regions",
    "Fiji" to "divisions",
    "Finland" to "regions",
    "France" to "regions",
    "Gambia" to "regions",
    "Georgia" to "regions",
    "Germany" to "states",
    "Ghana" to "regions",
    "Greece" to "regions",
    "Grenada" to "parishes",
    "Guatemala" to "departments",
    "Guinea Bissau" to "regions",
    "Guinea" to "regions",
    "Guyana" to "regions",
    "Haiti" to "departments",
    "Honduras" to "departments",
    "Hungary" to "counties",
    "Iceland" to "municipalities",
    "India" to "states",
    "Iraq" to "governorates",
    "Ireland" to "counties",
    "Israel" to "districts",
    "Italy" to "regions",
    "Ivory Coast" to "districts",
    "Jamaica" to "parishes",
    "Japan" to "prefectures",
    "Jordan" to "governorates",
    "Kazakhstan" to "regions",
    "Kenya" to "counties",
    "Kosovo" to "municipalities",
    "Kuwait" to "governorates",
    "Kyrgyzstan" to "regions",
    "Latvia" to "municipalities",
    "Lebanon" to "governorates",
    "Lesotho" to "districts",
    "Liberia" to "counties",
    "Libya" to "districts",
    "Liechtenstein" to "municipalities",
    "Lithuania" to "counties",
    "Luxembourg" to "cantons",
    "Macedonia" to "municipalities",
    "Madagascar" to "regions",
    "Malawi" to "regions",
    "Malaysia" to "states",
    "Maldives" to "atolls",
    "Mali" to "regions",
    "Malta" to "districts",
    "Mauritania" to "regions",
    "Mauritius" to "islands",
    "Mexico" to "states",
    "Micronesia" to "states",
    "Moldova" to "districts",
    "Mongolia" to "aimags",
    "Montenegro" to "municipalities",
    "Morocco" to "regions",
    "Myanmar" to "states",
    "Namibia" to "regions",
    "New Zealand" to "regions",
    "Nicaragua" to "departments",
    "Niger" to "regions",
    "Nigeria" to "states",
    "Norway" to "counties",
    "Oman" to "governorates",
    "Palau" to "states",
    "Palestine" to "governorates",
    "Paraguay" to "departments",
    "Peru" to "regions",
    "Philippines" to "regions",
    "Poland" to "voivodeships",
    "Portugal" to "districts",
    "Qatar" to "municipalities",
    "Romania" to "counties",
    "Russia" to "federal subjects",
    "Saint Kitts and Nevis" to "parishes",
    "Saint Lucia" to "parishes",
    "Saint Vincent and the Grenadines" to "parishes",
    "Samoa" to "districts",
    "San Marino" to "castelli",
    "Sao Tome and Principe" to "municipalities",
    "Saudi Arabia" to "regions",
    "Senegal" to "regions",
    "Serbia" to "districts",
    "Seychelles" to "districts",
    "Sierra Leone" to "districts",
    "Singapore" to "districts",
    "Slovakia" to "regions",
    "Slovenia" to "municipalities",
    "Somalia" to "states",
    "South Sudan" to "states",
    "Spain" to "autonomous communities",
    "Sudan" to "states",
    "Suriname" to "districts",
    "Sweden" to "counties",
    "Switzerland" to "cantons",
    "Syria" to "governorates",
    "Tanzania" to "regions",
    "Togo" to "regions",
    "Trinidad and Tobago" to "regions",
    "Tunisia" to "governorates",
    "Turkmenistan" to "regions",
    "Tuvalu" to "municipalities",
    "Uganda" to "districts",
    "Ukraine" to "oblasts",
    "United Arab Emirates" to "emirates",
    "United Kingdom" to "countries",
    "United States of America" to "states",
    "Uruguay" to "departments",
    "Uzbekistan" to "regions",
    "Vatican City" to "rape rooms",
    "Venezuela" to "states",
    "Yemen" to "governorates",
)

val continents = mapOf(
    "Afghanistan" to "Asia",
    "Albania" to "Europe",
    "Algeria" to "Africa",
    "American Samoa" to "Oceania",
    "Andorra" to "Europe",
    "Angola" to "Africa",
    "Antarctica" to "Antarctica",
    "Antigua and Barbuda" to "North America",
    "Argentina" to "South America",
    "Armenia" to "Asia",
    "Aruba" to "North America",
    "Australia" to "Oceania",
    "Austria" to "Europe",
    "Azerbaijan" to "Asia",
    "Bahamas" to "North America",
    "Bahrain" to "Asia",
    "Bangladesh" to "Asia",
    "Barbados" to "North America",
    "Belarus" to "Europe",
    "Belgium" to "Europe",
    "Belize" to "North America",
    "Benin" to "Africa",
    "Bermuda" to "North America",
    "Bhutan" to "Asia",
    "Bolivia" to "South America",
    "Bosnia and Herzegovina" to "Europe",
    "Botswana" to "Africa",
    "Brazil" to "South America",
    "Brunei" to "Asia",
    "Bulgaria" to "Europe",
    "Burkina Faso" to "Africa",
    "Burundi" to "Africa",
    "Cambodia" to "Asia",
    "Cameroon" to "Africa",
    "Canada" to "North America",
    "Cape Verde" to "Africa",
    "Cayman Islands" to "North America",
    "Central African Republic" to "Africa",
    "Chad" to "Africa",
    "Chile" to "South America",
    "China" to "Asia",
    "Colombia" to "South America",
    "Comoros" to "Africa",
    "Congo (Brazzaville)" to "Africa",
    "Cook Islands" to "Oceania",
    "Costa Rica" to "North America",
    "Croatia" to "Europe",
    "Cuba" to "North America",
    "Curacao" to "North America",
    "Cyprus" to "Asia",
    "Czech Republic" to "Europe",
    "DR Congo (Kinshasa)" to "Africa",
    "Denmark" to "Europe",
    "Djibouti" to "Africa",
    "Dominica" to "North America",
    "Dominican Republic" to "North America",
    "East Timor" to "Asia",
    "Ecuador" to "South America",
    "Egypt" to "Africa",
    "El Salvador" to "North America",
    "Equatorial Guinea" to "Africa",
    "Eritrea" to "Africa",
    "Estonia" to "Europe",
    "Ethiopia" to "Africa",
    "Falkland Islands" to "South America",
    "Fiji" to "Oceania",
    "Finland" to "Europe",
    "France" to "Europe",
    "French Polynesia" to "Oceania",
    "Gabon" to "Africa",
    "Gambia" to "Africa",
    "Georgia" to "Asia",
    "Germany" to "Europe",
    "Ghana" to "Africa",
    "Gibraltar" to "Europe",
    "Greece" to "Europe",
    "Greenland" to "North America",
    "Grenada" to "North America",
    "Guam" to "Oceania",
    "Guatemala" to "North America",
    "Guinea Bissau" to "Africa",
    "Guinea" to "Africa",
    "Guyana" to "South America",
    "Haiti" to "North America",
    "Honduras" to "North America",
    "Hong Kong" to "Asia",
    "Hungary" to "Europe",
    "Iceland" to "Europe",
    "India" to "Asia",
    "Indonesia" to "Asia",
    "Iran" to "Asia",
    "Iraq" to "Asia",
    "Ireland" to "Europe",
    "Israel" to "Asia",
    "Italy" to "Europe",
    "Ivory Coast" to "Africa",
    "Jamaica" to "North America",
    "Japan" to "Asia",
    "Jordan" to "Asia",
    "Kazakhstan" to "Asia",
    "Kenya" to "Africa",
    "Kiribati" to "Oceania",
    "Kosovo" to "Europe",
    "Kuwait" to "Asia",
    "Kyrgyzstan" to "Asia",
    "Laos" to "Asia",
    "Latvia" to "Europe",
    "Lebanon" to "Asia",
    "Lesotho" to "Africa",
    "Liberia" to "Africa",
    "Libya" to "Africa",
    "Liechtenstein" to "Europe",
    "Lithuania" to "Europe",
    "Luxembourg" to "Europe",
    "Macau" to "Asia",
    "Macedonia" to "Europe",
    "Madagascar" to "Africa",
    "Malawi" to "Africa",
    "Malaysia" to "Asia",
    "Maldives" to "Asia",
    "Mali" to "Africa",
    "Malta" to "Europe",
    "Marshall Islands" to "Oceania",
    "Mauritania" to "Africa",
    "Mauritius" to "Africa",
    "Mexico" to "North America",
    "Micronesia" to "Oceania",
    "Moldova" to "Europe",
    "Monaco" to "Europe",
    "Mongolia" to "Asia",
    "Montenegro" to "Europe",
    "Morocco" to "Africa",
    "Mozambique" to "Africa",
    "Myanmar" to "Asia",
    "Namibia" to "Africa",
    "Nepal" to "Asia",
    "Netherlands" to "Europe",
    "New Caledonia" to "Oceania",
    "New Zealand" to "Oceania",
    "Nicaragua" to "North America",
    "Niger" to "Africa",
    "Nigeria" to "Africa",
    "North Korea" to "Asia",
    "Northern Mariana Islands" to "Oceania",
    "Norway" to "Europe",
    "Oman" to "Asia",
    "Pakistan" to "Asia",
    "Palau" to "Oceania",
    "Palestine" to "Asia",
    "Panama" to "North America",
    "Papua New Guinea" to "Oceania",
    "Paraguay" to "South America",
    "Peru" to "South America",
    "Philippines" to "Asia",
    "Poland" to "Europe",
    "Portugal" to "Europe",
    "Puerto Rico" to "North America",
    "Qatar" to "Asia",
    "Romania" to "Europe",
    "Russia" to "Asia",
    "Rwanda" to "Africa",
    "Saint Kitts and Nevis" to "North America",
    "Saint Lucia" to "North America",
    "Saint Vincent and the Grenadines" to "North America",
    "Samoa" to "Oceania",
    "San Marino" to "Europe",
    "Sao Tome and Principe" to "Africa",
    "Saudi Arabia" to "Asia",
    "Senegal" to "Africa",
    "Serbia" to "Europe",
    "Seychelles" to "Africa",
    "Sierra Leone" to "Africa",
    "Singapore" to "Asia",
    "Slovakia" to "Europe",
    "Slovenia" to "Europe",
    "Solomon Islands" to "Oceania",
    "Somalia" to "Africa",
    "South Africa" to "Africa",
    "South Georgia and the Islands" to "Antarctica",
    "South Korea" to "Asia",
    "South Sudan" to "Africa",
    "Spain" to "Europe",
    "Sri Lanka" to "Asia",
    "Sudan" to "Africa",
    "Suriname" to "South America",
    "Svalbard and Jan Mayen Islands" to "Europe",
    "Swaziland" to "Africa",
    "Sweden" to "Europe",
    "Switzerland" to "Europe",
    "Syria" to "Asia",
    "Taiwan" to "Asia",
    "Tajikistan" to "Asia",
    "Tanzania" to "Africa",
    "Thailand" to "Asia",
    "Togo" to "Africa",
    "Tonga" to "Oceania",
    "Trinidad and Tobago" to "North America",
    "Tunisia" to "Africa",
    "Turkey" to "Asia",
    "Turkmenistan" to "Asia",
    "Turks and Caicos Islands" to "North America",
    "Tuvalu" to "Oceania",
    "Uganda" to "Africa",
    "Ukraine" to "Europe",
    "United Arab Emirates" to "Asia",
    "United Kingdom" to "Europe",
    "United States of America" to "North America",
    "Uruguay" to "South America",
    "Uzbekistan" to "Asia",
    "Vanuatu" to "Oceania",
    "Vatican City" to "Europe",
    "Venezuela" to "South America",
    "Vietnam" to "Asia",
    "Western Sahara" to "Africa",
    "Yemen" to "Asia",
    "Zambia" to "Africa",
    "Zimbabwe" to "Africa",
)

