package gay.depau.worldclock.mobile.ui.theme

// SPDX-License-Identifier: Apache-2.0
// This file is part of World Clock Tile.

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF7743B5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEEDBFF)
val md_theme_light_onPrimaryContainer = Color(0xFF2A0053)
val md_theme_light_secondary = Color(0xFF006B60)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF4FFBE5)
val md_theme_light_onSecondaryContainer = Color(0xFF00201C)
val md_theme_light_tertiary = Color(0xFF805159)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9DE)
val md_theme_light_onTertiaryContainer = Color(0xFF321018)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1D1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE8E0EB)
val md_theme_light_onSurfaceVariant = Color(0xFF4A454E)
val md_theme_light_outline = Color(0xFF7B757F)
val md_theme_light_inverseOnSurface = Color(0xFFF5EFF4)
val md_theme_light_inverseSurface = Color(0xFF322F33)
val md_theme_light_inversePrimary = Color(0xFFDAB9FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF7743B5)
val md_theme_light_outlineVariant = Color(0xFFCCC4CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFDAB9FF)
val md_theme_dark_onPrimary = Color(0xFF460283)
val md_theme_dark_primaryContainer = Color(0xFF5E289B)
val md_theme_dark_onPrimaryContainer = Color(0xFFEEDBFF)
val md_theme_dark_secondary = Color(0xFF17DEC9)
val md_theme_dark_onSecondary = Color(0xFF003731)
val md_theme_dark_secondaryContainer = Color(0xFF005048)
val md_theme_dark_onSecondaryContainer = Color(0xFF4FFBE5)
val md_theme_dark_tertiary = Color(0xFFF2B7C0)
val md_theme_dark_onTertiary = Color(0xFF4B252C)
val md_theme_dark_tertiaryContainer = Color(0xFF653B42)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9DE)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1B1E)
val md_theme_dark_onBackground = Color(0xFFE7E1E5)
val md_theme_dark_surface = Color(0xFF1D1B1E)
val md_theme_dark_onSurface = Color(0xFFE7E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF4A454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCCC4CF)
val md_theme_dark_outline = Color(0xFF958E98)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE7E1E5)
val md_theme_dark_inversePrimary = Color(0xFF7743B5)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFDAB9FF)
val md_theme_dark_outlineVariant = Color(0xFF4A454E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFBB86FC)
